version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
    volumes:
      - ./localstack-script:/etc/localstack/init/ready.d
      - "/var/run/docker.sock:/var/run/docker.sock"